### PR TITLE
[improve][broker] make managedLedgerOffloadedReadPriority compatible with broker property 

### PR DESCRIPTION
**Pull request by ethqunzhong**
This PR is for running tests for upstream PR [apache#17803](https://github.com/apache/pulsar/pull/17803)

### CODE REVIEW

**Comment by ethqunzhong** [comment]
This PR is for running tests for upstream PR https://github.com/apache/pulsar/pull/17803

**Comment by zhongyingqun** [comment]
test

**Comment by zhongyingqun** [comment]
LGTM

**Review by zhongyingqun — APPROVED** [review]

**Comment by ethqunzhong** [comment]
Merged

**Pull request closed without merging**
